parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"FG4G":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e={props:{changes:Object}};exports.default=e;
(function(){var t=exports.default||module.exports;"function"==typeof t&&(t=t.options),Object.assign(t,{render:function(){var t=this,s=t.$createElement,e=t._self._c||s;return e("ul",{staticClass:"lbvs-changes"},t._l(t.changes,function(s,n){return e("li",{key:n},[e("span",{attrs:{"data-status":s,title:t.$t("versions.label.status."+s)}},[t._v(" "+t._s(s)+" ")]),t._v(" "+t._s(n)+" ")])}),0)},staticRenderFns:[],_compiled:!0,_scopeId:null,functional:void 0});})();
},{}],"P5xL":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e={data:()=>({error:{message:null,details:{lockedModels:{}}}}),methods:{open(e){this.error=e,this.$refs.dialog.open()}}};exports.default=e;
(function(){var e=exports.default||module.exports;"function"==typeof e&&(e=e.options),Object.assign(e,{render:function(){var e=this,s=e.$createElement,t=e._self._c||s;return t("k-dialog",{ref:"dialog",staticClass:"lbvs-create-error-dialog",attrs:{"cancel-button":e.$t("close"),"submit-button":!1}},[t("p",{staticClass:"lbvs-create-error-dialog-message"},[e._v(" "+e._s(e.error.message)+" ")]),e._v(" "),t("ul",{staticClass:"lbvs-create-error-dialog-list"},e._l(e.error.details.lockedModels,function(s,r){return t("li",{key:r},[e._v(" "+e._s(r)+" "),t("span",[e._v("("+e._s(s.join(", "))+")")])])}),0)])},staticRenderFns:[],_compiled:!0,_scopeId:null,functional:void 0});})();
},{}],"BOz6":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e={data:()=>({instance:null,inProgress:!1,stagedChanges:{}}),computed:{fields(){return{label:{autofocus:!0,icon:"title",label:this.$t("versions.label.label"),type:"text"}}}},methods:{async onSubmit(){if(!0!==this.inProgress)try{this.inProgress=!0;let s=this.$refs.form.value.label;if(!s)throw this.$t("field.required");await this.$store.dispatch({type:"versions/createVersion",instance:this.instance,label:s}),this.$store.dispatch("notification/success",":)"),this.$refs.dialog.close()}catch(e){this.$refs.dialog.error(e.message||e)}finally{this.inProgress=!1}},async open(e){this.instance=e;try{this.stagedChanges=await this.$store.dispatch({type:"versions/prepareVersionCreation",instance:this.instance})}catch(s){if("error.versions.lockFiles"===s.key)return this.$refs.errorDialog.open(s);throw s}this.$refs.dialog.open()}}};exports.default=e;
(function(){var e=exports.default||module.exports;"function"==typeof e&&(e=e.options),Object.assign(e,{render:function(){var e=this,t=e.$createElement,s=e._self._c||t;return s("div",[s("k-dialog",{ref:"dialog",attrs:{size:"large","submit-button":e.$t("versions.button.create"),theme:"positive"},on:{submit:e.onSubmit}},[s("k-form",{ref:"form",attrs:{fields:e.fields},on:{submit:e.onSubmit},scopedSlots:e._u([{key:"header",fn:function(){return[s("k-field",{staticClass:"lbvs-create-changes",attrs:{label:e.$t("versions.label.changes")}},[s("lbvs-changes",{attrs:{changes:e.stagedChanges}})],1)]},proxy:!0}])})],1),e._v(" "),s("lbvs-create-error-dialog",{ref:"errorDialog"})],1)},staticRenderFns:[],_compiled:!0,_scopeId:null,functional:void 0});})();
},{}],"ytRD":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var s={data:()=>({inProgress:!1,version:null}),methods:{async onSubmit(){if(!0!==this.inProgress)try{this.inProgress=!0,await this.$store.dispatch({type:"versions/deleteVersion",version:this.version.name}),this.$store.dispatch("notification/success",":)"),this.$refs.dialog.close()}catch(s){this.$refs.dialog.error(s.message||s)}finally{this.inProgress=!1}},open(s){this.version=s,this.$refs.dialog.open()}}};exports.default=s;
(function(){var e=exports.default||module.exports;"function"==typeof e&&(e=e.options),Object.assign(e,{render:function(){var e=this,t=e.$createElement,s=e._self._c||t;return s("k-dialog",{ref:"dialog",staticClass:"lbvs-version-delete-dialog lbvs-version-dialog",attrs:{icon:"trash","submit-button":e.$t("versions.button.delete"),theme:"negative"},on:{submit:e.onSubmit}},[e.version?s("lbvs-version",{attrs:{version:e.version}}):e._e(),e._v(" "),s("p",[e._v(e._s(e.$t("versions.message.delete")))])],1)},staticRenderFns:[],_compiled:!0,_scopeId:null,functional:void 0});})();
},{}],"O9Nh":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e={data:()=>({inProgress:!1,version:null}),computed:{fields(){let e=this.$store.getters["versions/currentInstance"],s=Object.values(this.$store.state.versions.data.instances).map(e=>({text:e.name,value:e.name}));return{instance:{disabled:s.length<=1,empty:!1,icon:"box",label:this.$t("versions.label.targetInstance"),options:s,placeholder:e.name,type:"select",value:e.name}}}},methods:{async onSubmit(){if(!0!==this.inProgress)try{this.inProgress=!0;let s=this.$refs.form.value.instance||this.$store.getters["versions/currentInstance"].name;await this.$store.dispatch({type:"versions/deployVersion",version:this.version.name,instance:s}),this.$store.dispatch("notification/success",":)"),this.$refs.dialog.close()}catch(e){this.$refs.dialog.error(e.message||e)}finally{this.inProgress=!1}},open(e){this.version=e,this.$refs.dialog.open()}}};exports.default=e;
(function(){var t=exports.default||module.exports;"function"==typeof t&&(t=t.options),Object.assign(t,{render:function(){var t=this,e=t.$createElement,o=t._self._c||e;return o("k-dialog",{ref:"dialog",staticClass:"lbvs-version-dialog",attrs:{"submit-button":t.$t("versions.button.deploy"),theme:"positive"},on:{submit:t.onSubmit}},[t.version?o("lbvs-version",{attrs:{version:t.version}}):t._e(),t._v(" "),o("k-form",{ref:"form",attrs:{fields:t.fields},on:{submit:t.onSubmit}})],1)},staticRenderFns:[],_compiled:!0,_scopeId:null,functional:void 0});})();
},{}],"bZDy":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var t={data:()=>({data:null,version:{}}),computed:{details(){return this.data?[{title:this.$t("versions.label.fileSize"),value:this.data.filesize}]:[]},supportsClipboard(){try{return window.navigator.clipboard.writeText,!0}catch(t){return!1}}},methods:{async copyToClipboard(){await window.navigator.clipboard.writeText(this.data.url),this.$store.dispatch("notification/success",":)")},download(){window.location=this.data.url,this.$store.dispatch("notification/success",":)")},async open(t){this.data=null,this.version=t,this.$refs.dialog.open();let i=await this.$store.dispatch({type:"versions/exportVersion",version:this.version.name});t===this.version&&(this.data=i)}}};exports.default=t;
(function(){var o=exports.default||module.exports;"function"==typeof o&&(o=o.options),Object.assign(o,{render:function(){var o=this,t=o.$createElement,s=o._self._c||t;return s("k-dialog",{ref:"dialog",staticClass:"lbvs-version-dialog",attrs:{"cancel-button":o.$t(o.data?"close":"cancel"),"submit-button":!1}},[o.version?s("lbvs-version",{attrs:{details:o.details,version:o.version}}):o._e(),o._v(" "),o.data?s("k-button-group",[s("k-button",{attrs:{icon:"download"},on:{click:o.download}},[o._v(" "+o._s(o.$t("versions.button.download"))+" ")]),o._v(" "),s("k-button",{attrs:{icon:"copy",disabled:!o.supportsClipboard},on:{click:o.copyToClipboard}},[o._v(" "+o._s(o.$t("versions.button.copyLink"))+" ")])],1):s("p",[o._v(" "+o._s(o.$t("versions.message.exporting"))+" ")])],1)},staticRenderFns:[],_compiled:!0,_scopeId:null,functional:void 0});})();
},{}],"kxM1":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e={props:{inline:Boolean,instance:Object},computed:{element(){return this.inline?"span":"strong"}}};exports.default=e;
(function(){var t=exports.default||module.exports;"function"==typeof t&&(t=t.options),Object.assign(t,{render:function(){var t=this.$createElement;return(this._self._c||t)(this.element,{tag:"component",staticClass:"lbvs-instance-name",style:{backgroundColor:this.instance.color}},[this._v(" "+this._s(this.instance.name)+" ")])},staticRenderFns:[],_compiled:!0,_scopeId:null,functional:void 0});})();
},{}],"iR3R":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e={computed:{canCreateVersion(){return!0===this.$permissions["lukasbestle.versions"].create&&Object.keys(this.currentChanges).length>0},currentChanges(){return this.$store.getters["versions/currentInstance"].changes}},methods:{onCreate(){let e=this.$store.getters["versions/currentInstance"].name;return this.$refs.createDialog.open(e)}}};exports.default=e;
(function(){var s=exports.default||module.exports;"function"==typeof s&&(s=s.options),Object.assign(s,{render:function(){var s=this,e=s.$createElement,t=s._self._c||e;return t("div",{staticClass:"lbvs-status"},[t("k-view",[t("k-grid",[t("k-column",{attrs:{width:"1/3"}},[t("header",{staticClass:"k-section-header"},[t("k-headline",[s._v(" "+s._s(s.$t("versions.label.instances"))+" ")])],1),s._v(" "),t("ul",{staticClass:"lbvs-status-instances"},s._l(s.$store.state.versions.data.instances,function(e){return t("li",{key:e.name,class:{current:e.isCurrent}},[t("lbvs-instance-name",{attrs:{instance:e}}),s._v(" "),e.isCurrent?t("span",{staticClass:"lbvs-status-current"},[s._v(" "+s._s(s.$t("versions.label.current"))+" ")]):s._e(),s._v(" "),e.version?t("lbvs-version",{attrs:{version:{name:e.version,label:e.versionLabel}}}):s._e()],1)}),0)]),s._v(" "),t("k-column",{staticClass:"lbvs-status-changes",attrs:{width:"2/3"}},[t("header",{staticClass:"k-section-header"},[t("k-headline",[s._v(" "+s._s(s.$t("versions.label.changes"))+" ")]),s._v(" "),t("k-button-group",[t("k-button",{attrs:{icon:"add",disabled:!1===s.canCreateVersion},on:{click:s.onCreate}},[s._v(" "+s._s(s.$t("versions.button.create"))+" ")])],1)],1),s._v(" "),t("lbvs-changes",{attrs:{changes:s.currentChanges}})],1)],1)],1),s._v(" "),t("lbvs-create-dialog",{ref:"createDialog"})],1)},staticRenderFns:[],_compiled:!0,_scopeId:null,functional:void 0});})();
},{}],"OuAD":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e={props:{details:{type:Array,default:()=>[]},instances:Boolean,version:Object},computed:{mergedDetails(){return[{title:this.$t("versions.label.versionName"),value:this.version.name},...this.details].filter(e=>e.value)}}};exports.default=e;
(function(){var e=exports.default||module.exports;"function"==typeof e&&(e=e.options),Object.assign(e,{render:function(){var e=this,t=e.$createElement,s=e._self._c||t;return s("div",{staticClass:"lbvs-version"},[s("span",{staticClass:"lbvs-version-header"},[s("strong",[e._v(e._s(e.version.label))]),e._v(" "),e.instances?e._l(e.version.instances,function(t){return s("lbvs-instance-name",{key:t,attrs:{inline:!0,instance:e.$store.state.versions.data.instances[t]}})}):e._e()],2),e._v(" "),s("dl",{staticClass:"lbvs-version-details"},[e._l(e.mergedDetails,function(t){return[s("dt",{key:t.title,staticClass:"k-offscreen"},[e._v(" "+e._s(t.title)+": ")]),e._v(" "),s("dd",{key:t.title,attrs:{title:t.title}},[e._v(" "+e._s(t.value)+" ")])]})],2)])},staticRenderFns:[],_compiled:!0,_scopeId:null,functional:void 0});})();
},{}],"iyzB":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e={computed:{items(){return Object.values(this.$store.state.versions.data.versions)}},methods:{onOption(e,t){return this.$refs[e+"Dialog"].open(t)},options(e){let t=this.$permissions["lukasbestle.versions"];return[{click:"export",disabled:!0!==t.export,icon:"download",text:this.$t("versions.button.export")},{click:"deploy",disabled:!0!==t.deploy,icon:"wand",text:this.$t("versions.button.deploy")},{click:"delete",disabled:!0!==t.delete||e.instances.length>0,icon:"trash",text:this.$t("versions.button.delete")}]},versionDetails(e){return[{title:this.$t("versions.label.creation"),value:this.versionDetailsToString("creationData",{created:e.created?this.$library.dayjs.unix(e.created).format("YYYY-MM-DD HH:mm"):"?",creator:e.creatorName||e.creatorEmail||"?"})},{title:this.$t("versions.label.originInstance"),value:this.versionDetailsToString("from",{originInstance:e.originInstance||"?"})}]},versionDetailsToString(e,t){return!0===Object.values(t).every(e=>"?"===e)?null:this.$t("versions.label."+e,t)}}};exports.default=e;
(function(){var e=exports.default||module.exports;"function"==typeof e&&(e=e.options),Object.assign(e,{render:function(){var e=this,t=e.$createElement,s=e._self._c||t;return s("div",{staticClass:"lbvs-versions"},[s("k-view",[s("header",{staticClass:"k-section-header"},[s("k-headline",[e._v(" "+e._s(e.$t("versions.label.versions"))+" ")])],1),e._v(" "),e.items.length?s("k-list",e._l(e.items,function(t,i){return s("k-list-item",e._b({key:i,attrs:{image:!0,options:e.options(t)},on:{action:function(s){return e.onOption(s,t)}},scopedSlots:e._u([{key:"image",fn:function(){return[e._v(" "+e._s(i+1)+" ")]},proxy:!0}],null,!0)},"k-list-item",t,!1),[e._v(" "),s("lbvs-version",{attrs:{details:e.versionDetails(t),instances:!0,version:t}})],1)}),1):s("k-empty",{attrs:{layout:"cards"}},[e._v(" "+e._s(e.$t("versions.label.empty"))+" ")])],1),e._v(" "),s("lbvs-export-dialog",{ref:"exportDialog"}),e._v(" "),s("lbvs-deploy-dialog",{ref:"deployDialog"}),e._v(" "),s("lbvs-delete-dialog",{ref:"deleteDialog"})],1)},staticRenderFns:[],_compiled:!0,_scopeId:null,functional:void 0});})();
},{}],"vKFU":[function(require,module,exports) {

},{}],"q4Jg":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var s={data:()=>({isLoading:!0}),async mounted(){!0!==this.$permissions["lukasbestle.versions"].access&&this.$go("/");try{this.isLoading=!0,this.$store.dispatch("title",this.$t("view.versions")),await this.$store.dispatch("versions/load")}finally{this.isLoading=!1}}};exports.default=s;
(function(){var s=exports.default||module.exports;"function"==typeof s&&(s=s.options),Object.assign(s,{render:function(){var s=this.$createElement,t=this._self._c||s;return t("div",{staticClass:"lbvs-view"},[this.isLoading?t("k-loader"):[t("lbvs-status"),this._v(" "),t("lbvs-versions")]],2)},staticRenderFns:[],_compiled:!0,_scopeId:null,functional:void 0});})();
},{"../index.css":"vKFU"}],"iz0v":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=e=>({namespaced:!0,state:{data:{instances:{},versions:{}}},getters:{currentInstance:e=>Object.values(e.data.instances).find(e=>e.isCurrent)},mutations:{SET_DATA(e,{instances:s,versions:a}){e.data.instances=s,e.data.versions=a}},actions:{async load({commit:s}){s("SET_DATA",await e.$api.get("versions"))},prepareVersionCreation:async(s,{instance:a})=>await e.$api.post("versions/prepareCreation",{instance:a}),async createVersion({commit:s},{instance:a,label:n}){s("SET_DATA",await e.$api.post("versions/create",{instance:a,label:n}))},async deleteVersion({commit:s},{version:a}){s("SET_DATA",await e.$api.delete("versions/versions/"+a))},async deployVersion({commit:s},{instance:a,version:n}){s("SET_DATA",await e.$api.post("versions/versions/"+n+"/deploy",{instance:a}))},exportVersion:async(s,{version:a})=>await e.$api.post("versions/versions/"+a+"/export")}});exports.default=e;
},{}],"Focm":[function(require,module,exports) {
"use strict";var e=d(require("./components/Misc/Changes.vue")),s=d(require("./components/Dialogs/CreateErrorDialog.vue")),o=d(require("./components/Dialogs/CreateDialog.vue")),r=d(require("./components/Dialogs/DeleteDialog.vue")),l=d(require("./components/Dialogs/DeployDialog.vue")),t=d(require("./components/Dialogs/ExportDialog.vue")),i=d(require("./components/Misc/InstanceName.vue")),n=d(require("./components/Status.vue")),a=d(require("./components/Misc/Version.vue")),u=d(require("./components/Versions.vue")),v=d(require("./components/View.vue")),c=d(require("./store.js"));function d(e){return e&&e.__esModule?e:{default:e}}panel.plugin("lukasbestle/versions",{components:{"lbvs-changes":e.default,"lbvs-create-error-dialog":s.default,"lbvs-create-dialog":o.default,"lbvs-delete-dialog":r.default,"lbvs-deploy-dialog":l.default,"lbvs-export-dialog":t.default,"lbvs-instance-name":i.default,"lbvs-status":n.default,"lbvs-version":a.default,"lbvs-versions":u.default},views:{versions:{component:v.default,icon:"layers",menu:e=>!0===e.$permissions["lukasbestle.versions"].access||"disabled"}},created(e){e.$store.registerModule("versions",(0,c.default)(e))}});
},{"./components/Misc/Changes.vue":"FG4G","./components/Dialogs/CreateErrorDialog.vue":"P5xL","./components/Dialogs/CreateDialog.vue":"BOz6","./components/Dialogs/DeleteDialog.vue":"ytRD","./components/Dialogs/DeployDialog.vue":"O9Nh","./components/Dialogs/ExportDialog.vue":"bZDy","./components/Misc/InstanceName.vue":"kxM1","./components/Status.vue":"iR3R","./components/Misc/Version.vue":"OuAD","./components/Versions.vue":"iyzB","./components/View.vue":"q4Jg","./store.js":"iz0v"}]},{},["Focm"], null)